// frontend/components/Hero.vue
<template>
  <div class="relative flex col justify-end items-center w-full hero">
    <div class="gradient-bg"></div>
    <h2 class="hero-sub-title">
      14th Annual Business Forum for Young Professionals
    </h2>
    <h1 class="hero-title">
      Equipping & Empowering Tomorrow's Leaders
    </h1>
    <div class="flex row my-1 hero-btns">
      <button class="btn btn-primary-ghost" v-on:click="linkPage('forum')">Learn More</button>
      <button class="btn btn-primary" v-on:click="linkPage('loginRegister')">Register</button>
    </div>
  </div>
</template>

<script lang="ts">
export default {
  methods: {
    linkPage(page: string) {
      this.$router.push(`/${page}`);
    }
  }
}
</script>

<style lang="scss">
.gradient-bg {
  position: absolute;
  background: linear-gradient(to top, $uc-blue, rgba(255, 255, 255, 0.0));
  width: 100%;
  height: 100%;
  z-index: 0;
}

.hero {
  height: 25rem;
  background-color: $uc-red;
  overflow: hidden;
  background-image: url("/images/conference-1.jpg");
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
}

.hero-title {
  font-family: $font;
  font-size: 2.5rem;
  font-weight: 300;
  color: $gray-200;
  z-index: 1;
}

.hero-sub-title {
  font-family: $font;
  font-size: 1.5rem;
  font-style: italic;
  color: $gray-200;
  z-index: 1;
}

.hero-btns {
  z-index: 1;
}
</style>

// frontend/src/lib/components/Hero.svelte
<script>
</script>

<div class="relative flex flex-col w-full hero">
    <div>
        <div class="relative flex flex-col w-full h-full justify-end items-center hero-inside">
            <div class="relative flex flex-row justify-center items-center hero-title">
                <h1 class="gray-200">Hero Title</h1>
            </div>
        </div>
    </div>
</div>

<style>
    .hero {
        height: auto;
        background-image: url('/public/microphone.jpg');
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        margin-bottom: 3rem;
    }
    .hero-inside {
        height: 20rem;
    }
    .hero-title {
        width: 30rem;
        height: 6rem;
        margin-bottom: -2rem;
        background: linear-gradient(to bottom right, rgba(75, 85, 99, .35), rgba(229, 231, 235, .35));
        border-radius: 1em;
        backdrop-filter: blur(10px);
        border: 1px solid rgba(109, 40, 217, 0.05);
        background-clip: padding-box;
        box-shadow: 10px 15px 40px rgba(0, 0, 0, .50);
    }
</style>
